// Mocks generated by Mockito 5.4.4 from annotations
// in lumina/test/epub_import_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fpdart/fpdart.dart' as _i6;
import 'package:lumina/src/features/library/data/book_manifest_repository.dart'
    as _i8;
import 'package:lumina/src/features/library/data/shelf_book_repository.dart'
    as _i3;
import 'package:lumina/src/features/library/domain/book_manifest.dart' as _i9;
import 'package:lumina/src/features/library/domain/shelf_book.dart' as _i5;
import 'package:lumina/src/features/library/domain/shelf_group.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeShelfGroup_0 extends _i1.SmartFake implements _i2.ShelfGroup {
  _FakeShelfGroup_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ShelfBookRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShelfBookRepository extends _i1.Mock
    implements _i3.ShelfBookRepository {
  MockShelfBookRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.ShelfBook>> getAllBooks() => (super.noSuchMethod(
        Invocation.method(
          #getAllBooks,
          [],
        ),
        returnValue: _i4.Future<List<_i5.ShelfBook>>.value(<_i5.ShelfBook>[]),
      ) as _i4.Future<List<_i5.ShelfBook>>);

  @override
  _i4.Future<Set<String>> getAllNotDeletedFileHashes() => (super.noSuchMethod(
        Invocation.method(
          #getAllNotDeletedFileHashes,
          [],
        ),
        returnValue: _i4.Future<Set<String>>.value(<String>{}),
      ) as _i4.Future<Set<String>>);

  @override
  _i4.Future<List<_i5.ShelfBook>> getBooksSorted({
    _i3.ShelfBookSortBy? sortBy = _i3.ShelfBookSortBy.recentlyAdded,
    String? groupName,
    bool? includeAll = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBooksSorted,
          [],
          {
            #sortBy: sortBy,
            #groupName: groupName,
            #includeAll: includeAll,
          },
        ),
        returnValue: _i4.Future<List<_i5.ShelfBook>>.value(<_i5.ShelfBook>[]),
      ) as _i4.Future<List<_i5.ShelfBook>>);

  @override
  _i4.Future<List<_i2.ShelfGroup>> getGroups() => (super.noSuchMethod(
        Invocation.method(
          #getGroups,
          [],
        ),
        returnValue: _i4.Future<List<_i2.ShelfGroup>>.value(<_i2.ShelfGroup>[]),
      ) as _i4.Future<List<_i2.ShelfGroup>>);

  @override
  _i4.Future<_i2.ShelfGroup?> getGroupById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getGroupById,
          [id],
        ),
        returnValue: _i4.Future<_i2.ShelfGroup?>.value(),
      ) as _i4.Future<_i2.ShelfGroup?>);

  @override
  _i4.Future<_i2.ShelfGroup?> getGroupByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGroupByName,
          [name],
        ),
        returnValue: _i4.Future<_i2.ShelfGroup?>.value(),
      ) as _i4.Future<_i2.ShelfGroup?>);

  @override
  _i4.Future<_i2.ShelfGroup> saveGroup(_i2.ShelfGroup? group) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveGroup,
          [group],
        ),
        returnValue: _i4.Future<_i2.ShelfGroup>.value(_FakeShelfGroup_0(
          this,
          Invocation.method(
            #saveGroup,
            [group],
          ),
        )),
      ) as _i4.Future<_i2.ShelfGroup>);

  @override
  _i4.Future<_i6.Either<String, int>> createGroup({required String? name}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGroup,
          [],
          {#name: name},
        ),
        returnValue: _i4.Future<_i6.Either<String, int>>.value(
            _i7.dummyValue<_i6.Either<String, int>>(
          this,
          Invocation.method(
            #createGroup,
            [],
            {#name: name},
          ),
        )),
      ) as _i4.Future<_i6.Either<String, int>>);

  @override
  _i4.Future<_i6.Either<String, bool>> updateGroupName({
    required int? groupId,
    required String? name,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateGroupName,
          [],
          {
            #groupId: groupId,
            #name: name,
          },
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #updateGroupName,
            [],
            {
              #groupId: groupId,
              #name: name,
            },
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<_i6.Either<String, bool>> deleteGroup({required int? groupId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteGroup,
          [],
          {#groupId: groupId},
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #deleteGroup,
            [],
            {#groupId: groupId},
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<_i6.Either<String, bool>> updateBookGroup({
    required int? bookId,
    String? groupName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateBookGroup,
          [],
          {
            #bookId: bookId,
            #groupName: groupName,
          },
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #updateBookGroup,
            [],
            {
              #bookId: bookId,
              #groupName: groupName,
            },
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<_i6.Either<String, bool>> moveBooksToGroup({
    required Set<int>? bookIds,
    String? targetGroupName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #moveBooksToGroup,
          [],
          {
            #bookIds: bookIds,
            #targetGroupName: targetGroupName,
          },
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #moveBooksToGroup,
            [],
            {
              #bookIds: bookIds,
              #targetGroupName: targetGroupName,
            },
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<_i6.Either<String, bool>> softDeleteBook(int? bookId) =>
      (super.noSuchMethod(
        Invocation.method(
          #softDeleteBook,
          [bookId],
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #softDeleteBook,
            [bookId],
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<_i5.ShelfBook?> getBookById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getBookById,
          [id],
        ),
        returnValue: _i4.Future<_i5.ShelfBook?>.value(),
      ) as _i4.Future<_i5.ShelfBook?>);

  @override
  _i4.Future<_i5.ShelfBook?> getBookByHash(String? fileHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookByHash,
          [fileHash],
        ),
        returnValue: _i4.Future<_i5.ShelfBook?>.value(),
      ) as _i4.Future<_i5.ShelfBook?>);

  @override
  _i4.Future<bool> bookExists(String? fileHash) => (super.noSuchMethod(
        Invocation.method(
          #bookExists,
          [fileHash],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> bookExistsAndNotDeleted(String? fileHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #bookExistsAndNotDeleted,
          [fileHash],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<int> getBookIdByHash(String? fileHash) => (super.noSuchMethod(
        Invocation.method(
          #getBookIdByHash,
          [fileHash],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<_i6.Either<String, int>> saveBook(_i5.ShelfBook? book) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveBook,
          [book],
        ),
        returnValue: _i4.Future<_i6.Either<String, int>>.value(
            _i7.dummyValue<_i6.Either<String, int>>(
          this,
          Invocation.method(
            #saveBook,
            [book],
          ),
        )),
      ) as _i4.Future<_i6.Either<String, int>>);

  @override
  _i4.Future<_i6.Either<String, bool>> deleteBook(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBook,
          [id],
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #deleteBook,
            [id],
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<_i6.Either<String, bool>> updateProgress({
    required int? bookId,
    required int? currentChapterIndex,
    required double? progress,
    required double? scrollPosition,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProgress,
          [],
          {
            #bookId: bookId,
            #currentChapterIndex: currentChapterIndex,
            #progress: progress,
            #scrollPosition: scrollPosition,
          },
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #updateProgress,
            [],
            {
              #bookId: bookId,
              #currentChapterIndex: currentChapterIndex,
              #progress: progress,
              #scrollPosition: scrollPosition,
            },
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<_i6.Either<String, bool>> markAsFinished(int? bookId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsFinished,
          [bookId],
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #markAsFinished,
            [bookId],
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<List<_i5.ShelfBook>> getRecentBooks({int? limit = 10}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRecentBooks,
          [],
          {#limit: limit},
        ),
        returnValue: _i4.Future<List<_i5.ShelfBook>>.value(<_i5.ShelfBook>[]),
      ) as _i4.Future<List<_i5.ShelfBook>>);

  @override
  _i4.Future<List<_i5.ShelfBook>> searchBooks(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchBooks,
          [query],
        ),
        returnValue: _i4.Future<List<_i5.ShelfBook>>.value(<_i5.ShelfBook>[]),
      ) as _i4.Future<List<_i5.ShelfBook>>);
}

/// A class which mocks [BookManifestRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookManifestRepository extends _i1.Mock
    implements _i8.BookManifestRepository {
  MockBookManifestRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i9.BookManifest?> getManifestByHash(String? fileHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getManifestByHash,
          [fileHash],
        ),
        returnValue: _i4.Future<_i9.BookManifest?>.value(),
      ) as _i4.Future<_i9.BookManifest?>);

  @override
  _i4.Future<_i9.BookManifest?> getManifestById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getManifestById,
          [id],
        ),
        returnValue: _i4.Future<_i9.BookManifest?>.value(),
      ) as _i4.Future<_i9.BookManifest?>);

  @override
  _i4.Future<bool> manifestExists(String? fileHash) => (super.noSuchMethod(
        Invocation.method(
          #manifestExists,
          [fileHash],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<_i6.Either<String, int>> saveManifest(
          _i9.BookManifest? manifest) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveManifest,
          [manifest],
        ),
        returnValue: _i4.Future<_i6.Either<String, int>>.value(
            _i7.dummyValue<_i6.Either<String, int>>(
          this,
          Invocation.method(
            #saveManifest,
            [manifest],
          ),
        )),
      ) as _i4.Future<_i6.Either<String, int>>);

  @override
  _i4.Future<_i6.Either<String, bool>> deleteManifestByHash(String? fileHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteManifestByHash,
          [fileHash],
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #deleteManifestByHash,
            [fileHash],
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<_i6.Either<String, bool>> deleteManifest(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteManifest,
          [id],
        ),
        returnValue: _i4.Future<_i6.Either<String, bool>>.value(
            _i7.dummyValue<_i6.Either<String, bool>>(
          this,
          Invocation.method(
            #deleteManifest,
            [id],
          ),
        )),
      ) as _i4.Future<_i6.Either<String, bool>>);

  @override
  _i4.Future<List<_i9.BookManifest>> getAllManifests() => (super.noSuchMethod(
        Invocation.method(
          #getAllManifests,
          [],
        ),
        returnValue:
            _i4.Future<List<_i9.BookManifest>>.value(<_i9.BookManifest>[]),
      ) as _i4.Future<List<_i9.BookManifest>>);

  @override
  _i4.Future<_i9.SpineItem?> getSpineItemByIndex(
    String? fileHash,
    int? index,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSpineItemByIndex,
          [
            fileHash,
            index,
          ],
        ),
        returnValue: _i4.Future<_i9.SpineItem?>.value(),
      ) as _i4.Future<_i9.SpineItem?>);

  @override
  _i4.Future<int?> getSpineCount(String? fileHash) => (super.noSuchMethod(
        Invocation.method(
          #getSpineCount,
          [fileHash],
        ),
        returnValue: _i4.Future<int?>.value(),
      ) as _i4.Future<int?>);

  @override
  _i4.Future<List<_i9.TocItem>> getFlattenedToc(String? fileHash) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFlattenedToc,
          [fileHash],
        ),
        returnValue: _i4.Future<List<_i9.TocItem>>.value(<_i9.TocItem>[]),
      ) as _i4.Future<List<_i9.TocItem>>);
}
